development: &defaults
  extra:
    google_analytics_id: <%= ENV['GOOGLE_ANALYTICS_ID'] %>
  cors:
    allowed_origins: <%= ENV['CORS_ALLOWED_ORIGINS'] %>
    allowed_origins_regex: <%= ENV['CORS_ALLOWED_ORIGINS_REGEX'] %>
  media:
    max_size_mb: <%= ENV['MEDIA_MAX_SIZE_MB'] || 100 %>

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
