# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f673db1df68a192d0f74cd7f16e722e5798478a02d6e5530a61da2ba591e19c21535dfbf7120e6221a6f71088a6d5fd4c038523f691dea72cfa367ec9a781363

test:
  secret_key_base: e976096dacdafee70b94c741bccf4e6912f489fa87c7cac680782e67d5569e6d36e2758b06ac349ab023214d2276b18e39dedf8b49c1adcf8597d0fc947aa04e

staging:
  secret_key_base: <%= ENV["APP_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["APP_SECRET"] %>
